<?xml version="1.0" encoding="UTF-8" standalone="no"?><?xml-stylesheet type="text/css" href="Rule.css"?><!--<?xml-stylesheet type="text/xsl" href="rule.xsl"?>-->
<!DOCTYPE books[
    <!ELEMENT books (book)*>
    <!ELEMENT book(title,author)>
    <!ELEMENT title(#PCDATA)>
    <!ELEMENT author(#PCDATA)>
    <!ATTLIST book id ID #REQUIRED>
]>
<books>  
    <book id="1"> 
        <title>Title -: Web Programming</title> 
        <author>Author -: Chrisbates</author> 
       
         
    <price>200</price></book> 
    <book id="2"> 
        <title>Title -: Internet world-wide-web</title> 
        <author>Author -: Ditel</author> 
        
    </book> 
    <book id="3"> 
        <title>Title -: Computer Networks</title> 
        <author>Author -: Foruouzan</author> 
        
    </book> 
    <book id="4"> 
        <title>Title -: DBMS Concepts</title> 
        <author>Author -: Navath</author> 
        
    </book> 
    <book id="5"> 
        <title>Title -: Linux Programming</title> 
        <author>Author -: Subhitab Das</author> 
        
    </book> 
</books>